uploads = []
generated = []

[[outputs]]
id = "uwvpdqBKzuwq244N4eD0o"
uri = "file://igrejaapp-dist.tar.gz"
type = "unspecified"
title = "IgrejaApp - Sistema Compilado (dist)"

[[outputs]]
id = "PbmRKuEeQMUG_qKiud2Sz"
uri = "file://igrejaapp-dist.zip"
type = "unspecified"
title = "IgrejaApp - Completo com todas as mudanças"
